### ISSUE TITLE
Trouble charging mineral hoe

### ISSUE THREAD

**Issue by Thethuthinnang** [Resynth-Minecraft-Mod/Resynth-Mod#11]
Hello! I am really enjoying this mod. I just have one issue right now: I can't seem to re-charge a mineral hoe after initially creating and using it. I have tried it with mineral crystals in my inventory and in my hotbar, and I have tried sneak + right-clicking on mineral soil and mineral stone blocks, as well as other kinds of blocks (like grass). I've also tried holding a sneak + right-click on various blocks, in case it needed a charge-up time. I tried it also with both mineral crystals and the little mineral fragment pieces from mining the mineral stone in my inventory. Nothing seems to work. I feel that I'm probably making some very basic mistake. What might I be doing wrong? Is there a special kind of block we should be right-clicking or a specific slot in inventory where the crystals should be?

Here are some screenshots of where I had placed the mineral crystals:
![2019-04-04_11 30 11 trying to charge mineral hoe](https://user-images.githubusercontent.com/47260138/55572562-77d14a80-56cd-11e9-8dab-751d7ca8348b.png)
![2019-04-04_11 30 24 trying to charge mineral hoe](https://user-images.githubusercontent.com/47260138/55572564-77d14a80-56cd-11e9-8486-596c53956dbf.png)

Thank you so much for your help!

**Comment by LMelaia** [comment]
Hello! Unfortunately this seams to be a very rare bug. Simply discarding the Mineral Hoe that won't charge and replacing it with a new one fixed the issue for me when it appeared. Did you by any chance update the mod before the issue presented itself? I believe this is what caused the issue on my side. 

If replacing the Mineral Hoe does fix the issue, I may add a crafting recipe that allows crafting a new Mineral Hoe from the old one.

**Comment by Thethuthinnang** [comment]
Thanks for your quick response! I have been using just one version: 1.3.3. I downloaded it from CurseForge on Saturday. I'll try discarding the first mineral hoe. I made a second one, since I thought I might have to re-charge the first on mineral soil that didn't have anything planted, but I didn't try charging that one after I used it (they're both at 0 right now). I'll try that and report back. Thanks!

**Comment by Thethuthinnang** [comment]
Reporting back: It doesn't seem to work. The new hoe won't charge, either. I discarded the two I made previously and made a third one, but nothing seems to charge.
![2019-04-04_16 35 56](https://user-images.githubusercontent.com/47260138/55590403-6c474900-56f8-11e9-9428-e76ef1c9e39f.png)
I like the idea of a crafting recipe to fix it. Maybe a new crystal added to the old tool? Is it possible to configure the initial charge to last longer than 2 uses? I'm not sure if the charge usually uses up the crystal that's in your inventory, but a crafting fix could get a bit expensive if it's once every 2 uses.

Thank you so much for this mod and for looking into this issue! :)

**Comment by LMelaia** [comment]
While doing some testing to reproduce the results, I discovered what the issue is:

if an empty slot in your inventory is found before any mineral crystals, the hoe will skip over the rest of the inventory slots. It starts searching from left to right, starting in the hotbar, then searches top to bottom, left to right in the rest of the inventory slots. **So, keeping the mineral crystals in the very left slot in your hotbar, or, at the first open slot in the search order should work. If this fails, the mineral hoe can be charged in creative mode for no cost.**

Thanks for bringing the issue to my attention, I'll have an updated jar file out with the fix within the next couple of hours.

**Comment by Thethuthinnang** [comment]
Thank you! Changing the slot worked!

I see a notification for the update, so I'll download that, too. Thank you so much for working on this and resolving it so quickly, and thank you for this great mod. In one of my worlds, I'm focusing more on modded fantasy mobs and have vanilla mobs disabled, but certain drops are still needed for crafting, so this is a great way to work for those while maintaining the fantasy atmosphere. :)

**Comment by LMelaia** [comment]
Glad to help!

That's quite an interesting playthrough. I presume you've been using the Mystical Seed Pod to get the seeds?

**Comment by Thethuthinnang** [comment]
Yes, the pods have really helped so much! :) I have Ice and Fire, Aether, and other fantasy mods installed in this world, and I didn't really want to have vanilla mobs in the mix, if I could help it. The nether's still the nether, but I didn't want the overworld to have the usual vanilla feel.
