### ISSUE TITLE
Server Crashes With Mod Installed

### ISSUE THREAD

**Issue by TheMysticle** [Resynth-Minecraft-Mod/Resynth-Mod#15]
I was trying to run this mod on my server but everytime it crashes with the following.
[crash-2019-06-06_09.26.34-server.txt](https://github.com/Resynth-Minecraft-Mod/Resynth-Mod/files/3260704/crash-2019-06-06_09.26.34-server.txt)
Thanks in advance

**Comment by LMelaia** [comment]
Should be fixed with commit: 0c9b1dab91e284c7b6ab1e8a323f4e18b06aa126
