### ISSUE TITLE
Can't find certain modded materials

### ISSUE THREAD

**Issue by MBarnulf** [Resynth-Minecraft-Mod/Resynth-Mod#16]
Hello,
It seems like my game doesn't take certain modded materials into account, as an example, I also installed ExtremeReactor and, as mentioned in the wiki ( [this one](https://resynth-minecraft-mod.github.io/pages/wiki/integration.html) ) , Resynth should be able to add yellorite seeds but I'm unable to find them in creative or to give them to me.

screenshot:
![image](https://user-images.githubusercontent.com/52676082/61095960-0cc6ab00-a456-11e9-81ed-454bf022a6dd.png)

thank you in advance for your consideration

**Comment by MBarnulf** [comment]
PS:
- this is the latest actual release (mods AND forge)
- opened the config earlier but didn't tutched it's content
- installed Resynth AFTER ExtremeReactors

**Comment by LMelaia** [comment]
That's quite odd.

Off hand, I can't think what would be causing the problem. I assume that Resynth isn't able to create seeds for Extreme Reactors for some reason and then skipping them.

If you could attach a log file of one of the runs where the error occurs that would help a lot in debugging the problem.

**Comment by MBarnulf** [comment]
there are two logs from my game and my server running the same modpack, (I run 102 mods, so it will probably be hard to find something in there, but I don't know if I can do anything to make the work easier

[log[client].log](https://github.com/Resynth-Minecraft-Mod/Resynth-Mod/files/3459189/log.client.log)
[log[server].log](https://github.com/Resynth-Minecraft-Mod/Resynth-Mod/files/3459188/log.server.log)

**Comment by LMelaia** [comment]
The log files should be enough, thanks.

From what I can gather by looking at the logs, Resynth is finding Extreme Reactors, but it's failing to find the Extreme Reactors ore block, and then skipping the plant.

Other modded plants are being loaded so I assume it's a naming error with Extreme Reactors. I'll do some tests and see if I can reproduce the problem on my end and then fix it.

**Comment by LMelaia** [comment]
It turns out, the name Resynth uses to find the Yellorite Ore changed between the latest version (v0.4.5.67) of Extreme Reactors and the version it was originally tested on (0.4.5.48). This caused Resynth to not find the ore block on the latest release and fail to create the plant.

The next version of Resynth (v1.3.7) should fix this issue. Thanks for bringing it to my attention.

**Comment by MBarnulf** [comment]
Thanks you and have a nice day :D
