### ISSUE TITLE
Server Crash when using Mineral Hoe

### ISSUE THREAD

**Issue by johnneijzen** [Resynth-Minecraft-Mod/Resynth-Mod#18]
[crash-2019-09-23_01.11.27-server.txt](https://github.com/Resynth-Minecraft-Mod/Resynth-Mod/files/3639996/crash-2019-09-23_01.11.27-server.txt)

when right-clicking with Mineral Hoe on dirt become farmland but server also crash at same time

**Comment by LMelaia** [comment]
Hey there! This issue should be fixed with the next release.
