### ISSUE TITLE
potential server breakage

### ISSUE THREAD

**Issue by Warbringer12** [Resynth-Minecraft-Mod/Resynth-Mod#22]
[crash report server.TXT](https://github.com/Resynth-Minecraft-Mod/Resynth-Mod/files/3935824/crash.report.server.TXT)

**Comment by LMelaia** [comment]
Hi there! Could you please tell me what you did just before the crash happened?

**Comment by Warbringer12** [comment]
all i did was break a block and it crashed

**Comment by LMelaia** [comment]
I did some testing and couldn't get it to crash by breaking normal Vanilla blocks. Did you perhaps break a block from another mod?

**Comment by Warbringer12** [comment]
yes i did i was block from wildnature mod

**Comment by LMelaia** [comment]
Ah okay. I'll give Resynth a test with WildNature and some other mods to see if I can reproduce the error and fix it.

**Comment by LMelaia** [comment]
Hi again! My sincere apologies that this has taken so long. Normally things would be fixed much faster.

I have managed to fix the issue, at least, I think I have. I should be releasing a new version in the next couple of days with the fix. 

Thanks for making the problem known and helping diagnose it!
Ki11er_wolf
