### ISSUE TITLE
Unable to see Calvinite and Sylvanite 

### ISSUE THREAD

**Issue by lucifervii** [Resynth-Minecraft-Mod/Resynth-Mod#23]
I can't find Calvinite and Sylvanite blocks at all even with jei it's nowhere in the item list when I look at @resynth within jei

**Comment by LMelaia** [comment]
Are you in 1.12 by any chance? The enhancers weren’t added then.

If you’re using a version that does support them, I’d need to see the logs to have any idea what the issue would be.

**Comment by lucifervii** [comment]
Using 1.12.2

**Comment by LMelaia** [comment]
Calvinite, Sylvanite and the Enhancers aren't in the 1.12 versions.
I'm sorry.
