### ISSUE TITLE
Mineral Ore not imported to world, while Seeds are

### ISSUE THREAD

**Issue by IDrewAYoshi** [Resynth-Minecraft-Mod/Resynth-Mod#24]
First post, so I may need some patience as I learn. Thanks in advance.  I am using Forge 31.1.0 with Minecraft 1.15.2.   Upon importing the Resynth mod into my already created world, I see that I am able to obtain the seeds from minerals and mobs, but the actual Mineral Rocks do not generate.  I used an X-ray mod that shows only those Mineral Blocks to confirm this.  Is there something I am missing?

**Comment by LMelaia** [comment]
Hey there! Don't worry about it!

Minecraft only generates ores in the world when it is actually generating the world and terrain itself.
So the parts (called chunks) of your world that were generated before Resynth was added won't have the ore blocks. FYI this is the case for other mods as well, which generally makes adding ore gen mods to old worlds problematic.

You can still get the ores to generate in your already created world though. Simply, you'll have to walk a far way away and mine the ores there. If you see Mystical Seeds Pods start to show up, the ore will be generating there as well. New chunks are generated whenever you go exploring new parts of the world for the first time.

Hope this helps!
