### ISSUE TITLE
No mineral stone

### ISSUE THREAD

**Issue by jessiee135** [Resynth-Minecraft-Mod/Resynth-Mod#26]
Hi there, I have been mining on all levels between 10-2 at a 3x3 excavation. I’ve probably mines over 3000 blocks now. It says that this stone is very common but I haven’t found a single one of them. And yes I definitely have the mod installed and it is working.

**Comment by LMelaia** [comment]
Hey! I wouldn't call Mineral Stone common, per se, but 3,000 blocks is definitely excessive. 

Could you provide the Resynth version number you're playing on? Also, did you by any chance install Reysnth after creating the world?

As for now, I suggest bumping up the spawn rates, vein sizes, and spawn heights of Mineral Stone in the config and trying to find it in a brand new world. If you still can't find it then there's probably an issue with ore generation.

**Comment by jessiee135** [comment]
hey, the world was brand new, i had the mod installed before it was created. i'm playing on 4.1.0 for 1.15.2 forge.
How are configs changed? i couldn't find it

**Comment by LMelaia** [comment]
There will be a file called `general.toml` under `config\resynth` in your `.minecraft` folder where you can edit the config values with any text editor. If you're not sure where to find `.minecraft`, it should be under `C:\\Users\YourUserName\AppData\Roaming`. I'm assuming you're on Windows and using the standard - Mojang's - launcher.

In the config file will be a section that looks identical to this:


	[mineral-stone.ore-generation]
		#The maximum height (Y-level) that the ore blocks will generate
		#(type=integer, min=1, max=255, default=10)
		maximum-height = 10
		#The average count/frequency of ore veins in a chunk.
		#Set this number higher to increase the number of ore veins.
		#(type=integer, min=1, max=100, default=20)
		vein-count = 20
		#The minimum height (Y-level) that the ore blocks will generate.
		#(type=integer, min=0, max=255, default=0)
		bottom-offset = 0
		#Allows enabling or disabling generating the ore block in the world.
		#Set this to false to prevent the ore block from spawning in the world
		#(type=boolean, default=true)
		generate = true
		#The amount of blocks the ore block generation will be offset by on the Y-Axis.
		#(type=integer, min=0, max=255, default=0)
		top-offset = 0
		#The average size of the ore veins. Set this number
		#higher to increase the amount of ore blocks in an ore vein.
		#(type=integer, min=1, max=100, default=7)
		vein-size = 7

I suggest changing `vein-size` to 100, `vein-count` to 100, and `maximum-height` to 255, saving the file, starting Minecraft, and creating a new world. If after a couple minutes of mining at any level you still can't find any Mineral Stone, it's almost definitely a bug. If you do manage to find some, then I suggest setting the `vein-size` and `vein-count` to 2-4x the default values to make finding Mineral Stone in your normal world less challenging.
