### ISSUE TITLE
Plant Request: Cookies (Vanilla)

### ISSUE THREAD

**Issue by KXIIIS** [Resynth-Minecraft-Mod/Resynth-Mod#27]
Hello! I absolutely love this mod so much. May I ask for in a future update a seed that grows the vanilla cookie? That's all I ask for, it's simple but food is the way to my heart :) If not that's okay too but: this mod + cookies = happiness. Thanks for all your hard work regardless!

**Comment by LMelaia** [comment]
Hey there! Glad you like it - means a lot to me! :)

It shouldn't be particularly challenging to add a cookie plant, however, Resynth doesn't actually have a way to get seeds directly from items, only blocks and mobs. I'm sure I can get it done though - even if through a slightly unusual way - perhaps it may even be time for a new plant type that addresses this issue.

I'll update this ticket with a definite answer when I get around to working on it.

Almost forgot... which version of Minecraft are you using?

**Comment by KXIIIS** [comment]
Hey! I'm using 1.15.2. 

Ah, yes I didn't take into account how you would actually get a seed due to the nature of this mod. Hmm, I was so overtaken by my love of cookies that I didn't think it through :) That's my bad. I'm sure there's a way we just haven't thought of yet. Do you have an idea of how these new plant types would work or is it just a fresh idea for now? 

Thanks for your response!

**Comment by LMelaia** [comment]
Don't worry about it! Can always make a cookie block and treat it like an ore to get seeds. It's not the usual way, but it would work.

As for the new plant type, I've been thinking that I'm going to need them sooner or later, but I haven't given it much thought apart from that.

**Comment by KXIIIS** [comment]
Lol imagine strip mining and instead of finding diamonds, you find a random cookie block XD. I love it.

**Comment by KXIIIS** [comment]
Sorry, I accidentally clicked close.
Sounds good though. I'm sure you'll figure it out. :)

**Comment by KXIIIS** [comment]
So for the cookie block idea: 
1) You could make it an "ore" so when you mine it, it drops cookies with a chance to drop seeds. (It's a little OP but that's what mods are for lol)

2) You could have a crafting recipe to craft an edible cookie block that requires 9 cookies to make, which restores more hunger and saturation than a single cookie (obvi). Or you could place it down again as an "ore" and break it to try to get more seeds. 

Just some thoughts. If you don't like it or have something better, please feel free to share. I'm so excited about this idea XD

**Comment by KXIIIS** [comment]
Sorry, I accidentally closed it.

**Comment by KXIIIS** [comment]
Lol imagine strip mining and instead of finding diamonds, you find a random cookie block. I love it sm :)

**Comment by LMelaia** [comment]
I've found weird things while mining, so it wouldn't be a stretch XD.

But yeah, my current plan is just to make a compressed cookie block which can be blown up for seeds. I prefer this to mining the block as Metallic type plants grow faster. 

In the future I'll probably replace this with a new plant type, but until then, this should work :).

**Comment by KXIIIS** [comment]
Sounds awesome. I can’t wait :)
