### ISSUE TITLE
Ore Generation Fix & 1.16.4 Release?

### ISSUE THREAD

**Issue by TheGetGoodGit2211** [Resynth-Minecraft-Mod/Resynth-Mod#34]
Please can you try fix the ore gen problem. I know you said it's a bit broken, but other mods managed to generate ores fine, so it would be a real chad move to at least try to fix it. Furthermore, I have tested it and the latest 1.16.3 file does work on 1.16.4 (the version I primarily use).  Also, please attempt to update to 1.16.4 if you are not already. Thanks for reading and sorry if this is disturbing something you are currently doing.

**Comment by LMelaia** [comment]
Hi! I fully intend to fix the world generation, which will likely be done with the 1.16.4 release. So there is no need to worry that it won't be done. It just won't be very soon. As for the 1.16.3 release working on Minecraft 1.16.4 - I tested it and you are correct. I also updated the file on CurseForge as 1.16.4 compatible. Thanks for informing me!

**Comment by LMelaia** [comment]
Fixed with release 6.0.0
