### ISSUE TITLE
Netherite Scrap

### ISSUE THREAD

**Issue by Quaxel87** [Resynth-Minecraft-Mod/Resynth-Mod#35]
How i get the netherite scrap?

TNT dont work
i mined so much, but i dont get one

**Comment by LMelaia** [comment]
Hi! The Netherite plant, which grows Netherite Scrap, is actually a Crystalline type plant - which drops seeds when the ore block is  mined. **So, to get Netherite Seeds, you need to mine Ancient Debris.**

This is a bug. The plant should be a Metallic type and not a Crystalline type, so I understand the confusion.
I will fix this in the next version.
