### ISSUE TITLE
resynth "errors in datapack"

### ISSUE THREAD

**Issue by fearrrrrrrrr** [Resynth-Minecraft-Mod/Resynth-Mod#36]
LOG: https://pastebin.com/iW3TqN2P

I think the problem is that all of your items and their configured features are "unregistered." 

I belive that because of this, resynth is incompatible with the majority of mods that have their features registered.

I don't entirely know what "registered" means, but I suppose that you would.

the "blame" mod also seems to be freaking out and constantly filling up the log with this message:
 
"This ConfiguredFeature was found to be not registered. Look at the JSON info and try to
find which mod it belongs to. Then go tell that mod owner to register their ConfiguredFeature
as otherwise, it will break other mods or datapacks that registered their stuff."

**Comment by LMelaia** [comment]
Hey! Thanks for taking the time to inform me of this issue. The log was sadly no help at all, but from what you've said, I have a pretty good idea what the problem could be.

**Comment by LMelaia** [comment]
Fixed with release 6.0.0
