### ISSUE TITLE
i have thermal foundation in but can't get seeds from the ore 

### ISSUE THREAD

**Issue by killerofking96** [Resynth-Minecraft-Mod/Resynth-Mod#38]
I edit the configs to make it were it drop 100% of the time on copper as a test because I wasn't getting seeds and still ain't and yes I was mining thermal copper ore not some other mod. I'm playing on 1.12.2 
because minecraft crashes on anything higher because of overwolf. p.s. I'm getting all mobs and none thermal ore seeds

**Comment by LMelaia** [comment]
Hey! You are blowing up the ore blocks correct? With ores that need to be smelted, like Iron and Copper, seeds only drop when you blow the ores up with TNT. If you're pretty sure you're doing everything correctly and it's instead a problem with Resynth & Thermal, I suggest you try older versions first.

I'm sorry to say, I'm no longer developing (or even touching) 1.12.2 versions of Resynth, so there is no support for features that break. However, if you find anything, or have any more information or logs, you can post them here, and I'll have a look.

**Comment by LMelaia** [comment]
Closing this issue as it's not active.
