### ISSUE TITLE
Plant Request: Create Ores

### ISSUE THREAD

**Issue by yannick1124** [Resynth-Minecraft-Mod/Resynth-Mod#42]
Requested crops for: Copper (metallic, ore), Zinc (metallic, ore)
Mod: Create
Link to mod: https://www.curseforge.com/minecraft/mc-mods/create
Mods Minecraft Version: 1.16.5
Minecraft Version: 1.16.5

**Comment by yannick1124** [comment]
I didn't know how to add Labels, sorry

**Comment by LMelaia** [comment]
That's a good suggestion!

**Comment by LMelaia** [comment]
Expect the new crops for Copper and Zinc from Create in the next update! It should hopefully be released soon.
