### ISSUE TITLE
Changing specific config values causes strange unexpected behaviour

### ISSUE THREAD

**Issue by Dhgg2510** [Resynth-Minecraft-Mod/Resynth-Mod#43]
i have been tweaking the mod a little in the how much mineral ore i get and the plants time but every time i move anything related to the mineral blocks they appear, generate and show textures but breaking them doesn't give any resource instead when i put right click they respawn like i never touched them, is there something i can do about this?

**Comment by LMelaia** [comment]
Hi. I've tried many times to reproduce the bug you're describing with the latest Resynth version, however I couldn't find anything wrong with the ore or plant no matter how many config settings I change. Could you please state what version you're using as well as the things you did to cause the bug?

**Comment by Dhgg2510** [comment]
hi sorry for being late but i was running the latest version of the mod
with the 1.16.5 and i changed the mineral rock values wich made them
disappear and then reappear every time i hit them i solved it by erasing
and rebuilding the config file but every time i play with some values under
the mineral rock the bug reappears

**Comment by LMelaia** [comment]
Mod is no longer under development and has since been abandoned.
