### ISSUE TITLE
Resynth freezes on startup

### ISSUE THREAD

**Issue by thvless** [Resynth-Minecraft-Mod/Resynth-Mod#45]
- Running:
Forge 1.16.5 ver 36.1.25
Resynth 6.2.0
OptiFine 1.16.5 HD U G8

- Crash log:
[click me](https://pastebin.com/5brbNxst)

- The game simply freezes at the constructing x mods step and i'm forced to close it from the task manager. Removing resynth fixed the issue for good, although it seems to rarely get fixed by fiddling with the files, meaning sometimes deleting /config folder, adding or removing mods, changing the forge version all temporarily fixed the issue, but it keeps coming back. however recently nothing seemed to work until i removed resynth

**Comment by LMelaia** [comment]
Mod is no longer under development and has since been abandoned.
