### ISSUE TITLE
Plant Request: Copper and Cobbled Deepslate (Caves & Cliffs Backport)

### ISSUE THREAD

**Issue by micaCons** [Resynth-Minecraft-Mod/Resynth-Mod#46]
Requested crops for: Copper (metallic, ore) and Cobbled Deepslate (metallic)
Mod: Caves & Cliffs Backport
Link to mod: https://www.curseforge.com/minecraft/mc-mods/caves-and-cliffs-backport
Mods Minecraft Version: 1.16.5
Minecraft Version: 1.16.5

Mainly interested in the copper.

Love the mod, thank you!!

**Comment by LMelaia** [comment]
Mod is no longer under development and has since been abandoned.
