### ISSUE TITLE
[1.16.5] Crash on startup: mcjty.theoneprobe.api.ITextStyle.getAlignment

### ISSUE THREAD

**Issue by CodeGordon** [Resynth-Minecraft-Mod/Resynth-Mod#48]
I've tried an existing world and a new world, both single-player, with and without `spawnNote` active in TOP's settings.

[latest.log](https://github.com/Resynth-Minecraft-Mod/Resynth-Mod/files/6872779/latest.log)

[crash-2021-07-19_10.32.58-server.txt](https://github.com/Resynth-Minecraft-Mod/Resynth-Mod/files/6872780/crash-2021-07-19_10.32.58-server.txt)

I added TOP as a dependency and repacked the JAR file for Resynth, and still got the same error and crash.

[latest.log](https://github.com/Resynth-Minecraft-Mod/Resynth-Mod/files/6872787/latest.log)

[crash-2021-07-24_12.41.17-server.txt](https://github.com/Resynth-Minecraft-Mod/Resynth-Mod/files/6872786/crash-2021-07-24_12.41.17-server.txt)

Additional context: [TOP#499](https://github.com/McJtyMods/TheOneProbe/issues/499)

**Comment by LMelaia** [comment]
Mod is no longer under development and has since been abandoned.
