### ISSUE TITLE
[1.16.5] Crash on startup: java.lang.NullPointerException while ticking

### ISSUE THREAD

**Issue by CodeGordon** [Resynth-Minecraft-Mod/Resynth-Mod#49]
Randomly crashing on or shortly after startup in existing single-player world.

[2021-07-23-3.log](https://github.com/Resynth-Minecraft-Mod/Resynth-Mod/files/6872795/2021-07-23-3.log)

[crash-2021-07-23_20.03.06-server.txt](https://github.com/Resynth-Minecraft-Mod/Resynth-Mod/files/6872793/crash-2021-07-23_20.03.06-server.txt)

**Comment by NightOps007** [comment]
I get the same thing on my game. 👎

**Comment by LMelaia** [comment]
Mod is no longer under development and has since been abandoned.
