### ISSUE TITLE
1.12.2 Can't connect to servers anymore [Critical]

### ISSUE THREAD

**Issue by LLjo** [Resynth-Minecraft-Mod/Resynth-Mod#50]
Me and players on a server are getting "authentication servers are down" while using this mod now all of a sudden. It works using another mod launcher but using curseforge doesnt work. Any way to fix it?

I made a completely new profile on curseforge and added 1.3.9/1.3.8 and 1.3.3 and it wouldnt let me connect to a server

**Comment by LMelaia** [comment]
Mod is no longer under development and has since been abandoned.
