### ISSUE TITLE
invisible block

### ISSUE THREAD

**Issue by mortalfates** [Resynth-Minecraft-Mod/Resynth-Mod#51]
hello, someone on my server tried to use pistons to move mineral soil, resulting in my server crashing several times, after restarting, we discovered that the mineral didn't move but the area in front was unplacable for anything, I spawned barrier blocks to see if that was the issue, it was not, we now have 2 blocks seemingly unable to fix, tried restarting and stopping my server to no prevail.

**Comment by LMelaia** [comment]
Mod is no longer under development and has since been abandoned.
