### ISSUE TITLE
[1.16.5] Crash on startup when adding mod Resynth

### ISSUE THREAD

**Issue by ghost** [Resynth-Minecraft-Mod/Resynth-Mod#52]
Forge version: 36.2.33
Minecraft version: 1.16.5
TheOneProbe version: 3.1.5
Resynth version: 6.2.0

Hi, I wanted to try out your mod, but after adding mod, my game crashes on startup, crashlog bellow:

https://pastebin.com/RW662AL4

I posted issue on TheOneProbe github: https://github.com/McJtyMods/TheOneProbe/issues/549 and McJty said that you're using API wrong.

**Comment by LMelaia** [comment]
Mod is no longer under development and has since been abandoned.
