### ISSUE TITLE
No longer on curseforge?

### ISSUE THREAD

**Issue by YokoSilver** [Resynth-Minecraft-Mod/Resynth-Mod#53]
As the title says I can't find this mod anymore on curseforge meaning I can't download it anymore. Is there anywhere else I can download this mod?

**Comment by LMelaia** [comment]
Finally fixed: added GitHub Release with download links to All Resynth Versions and files from CurseForge.
https://github.com/Resynth-Minecraft-Mod/Resynth-Mod/releases/tag/minecraft-resynth-all-files
