### ISSUE TITLE
[SERVER] Crash on forge 1.12.2 (Works client side)

### ISSUE THREAD

**Issue by Mozza7** [Resynth-Minecraft-Mod/Resynth-Mod#8]
Error log can be found here:
https://pastebin.com/dB7HcTY0

Or downloaded below, along with other logs.

[crash-2019-02-23_17.33.27-server.txt](https://github.com/Resynth-Minecraft-Mod/Resynth-Mod/files/2897065/crash-2019-02-23_17.33.27-server.txt)

**Comment by LMelaia** [comment]
Hi Mozza7, thanks for the bug report. I can reproduce the bug on my side and I think I know what's causing it. I'll have a patch out in the next couple of days. I'll also do some testing and make sure the mod works on the servers side.

ps. I edited your message to exclude the last file (latest.txt) as it's not needed to fix the issue and it contains some personal information (such as directories and user names). I'd recommend you delete that file if you don't what that information getting out.

**Comment by Mozza7** [comment]
That's perfect, thank you. I'm in no rush for it- but I'll keep an eye out anyway :) Appreciate your help!

Oh and thanks! Hadn't realised, just wanted to give you as much info as possible :)

**Comment by LMelaia** [comment]
Anytime! Thanks for helping improve the mod by point out issues.
