### ISSUE TITLE
Agricraft support

### ISSUE THREAD

**Issue by vertex101** [Resynth-Minecraft-Mod/Resynth-Mod#9]
do you plan on adding support for the agricraft crop stiucks ?

**Comment by LMelaia** [comment]
I hadn't thought about it but I will look into adding support for the crop sticks after I've ported the mod to 1.13.2.

**Comment by vertex101** [comment]
okies if help is needed i can setup the stuff for agricraft n send a pull request to them to have it added into the mod i have done it a couple times before

**Comment by LMelaia** [comment]
Do you know if support for the crop sticks needs to be done on Agricrafts side or if there is an API for it?

**Comment by vertex101** [comment]
i have done it for a couple other mods i just took a script that was already made then edited for the way i wanted it this is the respo u can send pull requests to https://github.com/AgriCraft/AgriPlants and if u want to see how i done it the xlfoodmod is the one i added

**Comment by LMelaia** [comment]
Sadly, I don't think Agricraft support is happening. Mostly due to the complexity, personal time constraints, and it not being required to use Resynth. My apologies.
